#!/usr/bin/env bash
# This script configures a new server [web-02] same as the old one and configures
# a custom header file
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.artimus.tech permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
str2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str2/" /etc/nginx/sites-enabled/default
sudo service nginx restart
