#!/usr/bin/env bash
# this script installs and configures an new ubuntu machine to have HA proxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get install -y haproxy=2.6.\*
echo "ENABLED=1" |sudo tee -a /etc/default/haproxy
str1=\
"backend myback
	balance roundrobin
	server 115044-web-01 100.25.143.38:80 check
	server 115044-web-02 54.160.96.215:80 check
frontend myfront
	bind *:80
	mode http
	default_backend myback
"
echo "$str1" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
