#!/usr/bin/env bash
#copies file from one remote host to another
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
